name: sinUPsi
favicon: null
layout_spectrum: 0.6534785069525242
typography_spectrum: 0.1721508614718914
title: 'Network Planning & Design  |  Information Technology  |  Building Automation'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffada'
    - '#200003'
    - '#ded4b9'
    - '#a49582'
    - '#816e60'
  brandStrength: 0.8729169815778732
  lightness: 0.7241243205498904
  saturation: 0.10812632599845529
  rhythmicContrast: 0.9477274911478162
purpose: []
